apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: globalmart-postgres
    type: postgres
    access: proxy
    url: globalmart-postgres:5432
    database: globalmart
    user: globalmart
    secureJsonData:
      password: globalmart123
    jsonData:
      sslmode: disable
    isDefault: true
    editable: true
